
# server port
server:
  port: 8080

# Data Source
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/user
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: milk0147*
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  # Spring Data JPA(Java Persistence API)
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MariaDBDialect
        #show_sql: true
        format_sql: true
    open-in-view: false

# Logging level
logging.level:
  org.hibernate.SQL: debug

