
# server port
server:
  port: 8080

# Data Source
spring:
  datasource:
    url: jdbc:mariadb://43.201.109.135:3306/user
    driver-class-name: org.mariadb.jdbc.Driver
    username: byeon
    password: milk0147*
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  # Spring Data JPA(Java Persistence API)
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        #show_sql: true
        format_sql: true
    open-in-view: false

# Logging level
logging.level:
  org.hibernate.SQL: debug

# Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true # swagger ui 사용여부 (굳이 설정하지 않아도 default는 true)
    #version: 'v1' # API 문서 버전
  default-consumes-media-type: application/json # 기본 consume media type
  default-produces-media-type: application/json # 기본 produce media type
  model-and-view-allowed: true # ModelAndView 허용
  api-docs:
    path: /api-docs

