
# server port
server:
  port: 80

# Data Source
spring:
  datasource:
    url: jdbc:mariadb://join-db.crsyg0wgg0ss.ap-northeast-2.rds.amazonaws.com:3306/user
    driver-class-name: org.mariadb.jdbc.Driver
    username: admin
    password: milk0147*
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  # Spring Data JPA(Java Persistence API)
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MariaDBDialect
        #show_sql: true
        format_sql: true
    open-in-view: false

# Logging level
logging.level:
  org.hibernate.SQL: debug

